"""Generate filter coefficients for every downstream implementation.

Three programs filter the same ECG: the Python validation pipeline, the ESP32
firmware (C), and the ingest server (JavaScript). Designing the filters once here and
generating the other two removes the failure mode where the pipeline that was
validated and the pipeline that runs in production are quietly different pipelines.

Run after any change to :mod:`filters` or the detection band:

    python dsp/export_coefficients.py
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
from scipy import signal

from filters import FilterConfig, design_bandpass, design_notch, export_notch_header
from ppg import DEFAULT_FS as PPG_DEFAULT_FS
from pan_tompkins import QrsConfig

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "sim"))

from afe_model import AdcConfig, AfeConfig  # noqa: E402

C_HEADER = ROOT / "firmware" / "src" / "notch_coeffs.h"
C_CALIB = ROOT / "firmware" / "src" / "vs_calibration.h"
JS_MODULE = ROOT / "server" / "src" / "dsp" / "coefficients.js"

_BANNER = """// Auto-generated by dsp/export_coefficients.py - do not edit by hand.
// Regenerate with:  python dsp/export_coefficients.py
"""


def _sos_literal(sos: np.ndarray) -> str:
    """Render an SOS matrix as a JavaScript array-of-arrays."""
    rows = ",\n  ".join("[" + ", ".join(f"{v:.12g}" for v in row) + "]" for row in sos)
    return f"[\n  {rows},\n]"


#: Pulse band, matching `_pulsatile()` in dsp/ppg.py.
PPG_BAND_LOW = 0.5
PPG_BAND_HIGH = 5.0


def export_js(path: Path = JS_MODULE, cfg: FilterConfig | None = None, qrs: QrsConfig | None = None) -> Path:
    """Write the display filters and the QRS detection band as an ES module."""
    cfg = cfg or FilterConfig()
    qrs = qrs or QrsConfig(fs=cfg.fs)

    b, a = design_notch(cfg)
    b, a = b / a[0], a / a[0]  # normalise so a[0] == 1, the form the JS biquad assumes
    display_sos = design_bandpass(cfg)

    import ppg as _ppg

    ppg_rates = (100.0, 125.0)
    ppg_bands = "".join(
        f"  {int(rate)}: {_sos_literal(signal.butter(2, [PPG_BAND_LOW / (rate / 2), PPG_BAND_HIGH / (rate / 2)], btype='bandpass', output='sos')).replace(chr(10), chr(10) + '  ')},\n"
        for rate in ppg_rates
    )
    detect_sos = signal.butter(
        qrs.bp_order, [qrs.bp_low, qrs.bp_high], btype="bandpass", fs=qrs.fs, output="sos"
    )

    ppg_cal_intercept = _ppg.CAL_INTERCEPT
    ppg_cal_slope = _ppg.CAL_SLOPE
    ppg_min_perfusion = _ppg.MIN_PERFUSION_PCT
    ppg_min_r = _ppg.MIN_PLAUSIBLE_R
    ppg_max_r = _ppg.MAX_PLAUSIBLE_R
    ppg_min_bpm = _ppg.MIN_PULSE_BPM
    ppg_max_bpm = _ppg.MAX_PULSE_BPM
    ppg_min_corr = _ppg.MIN_CHANNEL_CORR
    ppg_good_corr = _ppg.GOOD_CHANNEL_CORR
    ppg_subharm = _ppg.SUBHARMONIC_TOLERANCE
    ppg_min_periodicity = _ppg.MIN_PERIODICITY

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""{_BANNER}//
// Shared by the Python validation pipeline, the ESP32 firmware and this server.

export const SAMPLE_RATE_HZ = {cfg.fs:g};

/** {cfg.notch_freq:g} Hz mains-rejection notch, Q = {cfg.notch_q:g}. Normalised so a[0] === 1. */
export const NOTCH = {{
  b: [{b[0]:.12g}, {b[1]:.12g}, {b[2]:.12g}],
  a: [{a[0]:.12g}, {a[1]:.12g}, {a[2]:.12g}],
}};

/**
 * Display path: {cfg.bp_low:g}-{cfg.bp_high:g} Hz Butterworth bandpass, order {cfg.bp_order}.
 * This is the waveform a clinician looks at - undistorted morphology.
 * Rows are [b0, b1, b2, a0, a1, a2].
 */
export const DISPLAY_SOS = {_sos_literal(display_sos)};

/**
 * Detection path: {qrs.bp_low:g}-{qrs.bp_high:g} Hz Butterworth bandpass, order {qrs.bp_order}.
 * Deliberately NOT the display band - it maximises QRS energy for the beat
 * detector at the cost of waveform fidelity (decision D-07).
 */
export const DETECTION_SOS = {_sos_literal(detect_sos)};

/** Pan-Tompkins timing parameters, in milliseconds unless noted. */
export const QRS_PARAMS = {{
  integrationMs: {qrs.integration_ms:g},
  refractoryMs: {qrs.refractory_ms:g},
  twaveMs: {qrs.twave_ms:g},
  twaveSlopeFrac: {qrs.twave_slope_frac:g},
  learningS: {qrs.learning_s:g},
  fiducialMs: {qrs.fiducial_ms:g},
  minSignalStd: {qrs.min_signal_std:g},
}};

/**
 * Pulse band for photoplethysmography: {PPG_BAND_LOW:g}-{PPG_BAND_HIGH:g} Hz, order 2, covering
 * {{MIN_PULSE_BPM}}-{{MAX_PULSE_BPM}} bpm and the first harmonic.
 *
 * Keyed by sample rate, because a PPG front end does not run at the ECG rate: the
 * MAX30102 defaults to 100 Hz and the BIDMC recordings used for validation are 125 Hz.
 * Applying one rate's coefficients to another's stream would silently move the band, so
 * the port refuses a rate that is not in this table rather than designing one at run
 * time (the same rule as D-14).
 */
export const PPG_BANDPASS_SOS = {{
{ppg_bands}}};

/** Thresholds from dsp/ppg.py - defined once, applied identically in both languages. */
export const PPG_PARAMS = {{
  calIntercept: {ppg_cal_intercept:g},
  calSlope: {ppg_cal_slope:g},
  minPerfusionPct: {ppg_min_perfusion:g},
  minPlausibleR: {ppg_min_r:g},
  maxPlausibleR: {ppg_max_r:g},
  minPulseBpm: {ppg_min_bpm:g},
  maxPulseBpm: {ppg_max_bpm:g},
  minChannelCorr: {ppg_min_corr:g},
  goodChannelCorr: {ppg_good_corr:g},
  subharmonicTolerance: {ppg_subharm:g},
  minPeriodicity: {ppg_min_periodicity:g},
}};
"""
    )
    return path


def export_calibration(path: Path = C_CALIB, afe: AfeConfig | None = None, adc: AdcConfig | None = None) -> Path:
    """Write the ADC-count to millivolt scaling the firmware needs, as a C header.

    The firmware has to turn ADC codes back into millivolts before it can put them in a
    frame, and that conversion depends on the amplifier gain, the reference level and
    the converter's full scale - the same three numbers `sim/afe_model.py` uses to
    validate the DSP. Hand-copying them into the firmware would let the device's idea of
    a millivolt drift away from the pipeline's, silently, in units nobody would notice
    were wrong until a heart rate looked odd (the same argument as D-12).

    Everything is emitted as integers: converting counts to millivolts in fixed point
    avoids linking floating-point printf into the image, which on an ESP32 costs flash
    and, in an ISR-adjacent path, time.
    """
    afe = afe or AfeConfig()
    adc = adc or AdcConfig()

    zero_code = round((afe.vref_v - adc.vmin_v) / adc.lsb_v)
    # Nanovolts at the electrodes per ADC count: one LSB of converter, divided by gain.
    nv_per_count = round(1e9 * adc.lsb_v / afe.gain)
    full_scale = adc.codes - 1
    # Rails are where the amplifier has clipped; leads-off railing lands here.
    rail_margin = round(0.02 * adc.codes)

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        f"""{_BANNER}//
// Acquisition scaling, generated from sim/afe_model.py - the same model the DSP is
// validated through. Do not hand-edit: the device's millivolt and the pipeline's
// millivolt must be the same millivolt.
#pragma once

#include <stdint.h>

#define VS_ADC_BITS          {adc.bits}
#define VS_ADC_FULL_SCALE    {full_scale}
#define VS_AFE_GAIN          {afe.gain:.0f}
#define VS_SUPPLY_MV         {round(afe.supply_v * 1000)}

// Code that corresponds to 0 mV at the electrodes (the mid-supply reference).
#define VS_ADC_ZERO_CODE     {zero_code}

// Nanovolts at the electrodes per ADC count: (Vfs / 2^bits) / gain.
// counts -> nV is one multiply; nV -> mV is a divide by 1e6 at format time.
#define VS_NV_PER_COUNT      {nv_per_count}

// Within this many codes of a rail, the amplifier has clipped. A detached electrode
// rails the AD8232 output, so this is a signal-side cross-check on the LO pins.
#define VS_RAIL_MARGIN       {rail_margin}

// Input range before the amplifier saturates, in microvolts (D-26: sized from the
// +/-5 mV that IEC 60601-2-27 expects an ECG monitor to accept).
#define VS_INPUT_RANGE_UV    {round(1e6 * min(afe.vref_v, afe.supply_v - afe.vref_v) / afe.gain)}
"""
    )
    return path


def export_all() -> list[Path]:
    """Regenerate every generated coefficient file."""
    return [export_notch_header(C_HEADER), export_calibration(C_CALIB), export_js(JS_MODULE)]


if __name__ == "__main__":
    for written in export_all():
        print(f"wrote {written.relative_to(ROOT)}")
