// Auto-generated by dsp/filters.py - do not edit by hand. Regenerate with:
//   python dsp/filters.py --export
// 50 Hz notch biquad, fs = 360 Hz, Q = 30
//   y[n] = b0*x[n] + b1*x[n-1] + b2*x[n-2] - a1*y[n-1] - a2*y[n-2]
#pragma once

#include <stdint.h>

#define VS_SAMPLE_RATE_HZ 360.0f

static const float NOTCH_B[3] = {0.9856631004f, -1.2671440565f, 0.9856631004f};
static const float NOTCH_A[3] = {1.0000000000f, -1.2671440565f, 0.9713262007f};

// Fixed-point form, Q14 (one unit = 1/16384). Quantised pole radius
// 0.985552 - checked < 1 at generation time, because rounding the
// coefficients moves the poles and a stable design can quantise into an unstable filter.
#define VS_NOTCH_FRAC_BITS 14
#define VS_NOTCH_ONE       (16384)

static const int16_t NOTCH_B_Q[3] = {16149, -20761, 16149};
static const int16_t NOTCH_A_Q[3] = {16384, -20761, 15914};
