/* Fixed-point 50 Hz mains-rejection notch for the acquisition path.
 *
 * Portable C99: no Arduino, no ESP-IDF, no floating point. That is deliberate. The
 * same translation unit is compiled into the ESP32 image and into the host test
 * harness, so the filter that runs on the device is the filter that gets scored
 * against the Python design on MIT-BIH (D-25). A filter that can only be exercised on
 * a board can only be trusted on a board.
 *
 * Coefficients come from firmware/src/notch_coeffs.h, generated by dsp/filters.py from
 * the same design the validation pipeline uses (D-12). They are never edited here.
 *
 * Why fixed point when the ESP32 has an FPU: the sampler runs from a timer ISR at
 * 360 Hz sharing a core with WiFi, and integer arithmetic has constant cost and a
 * bit-exact result across compilers and optimisation levels. Bit-exactness is what
 * makes the host score meaningful - a float build that rounded differently would be
 * scoring a different filter from the one that shipped.
 *
 * Signal representation: ADC counts, carried internally with VS_NOTCH_SAMPLE_FRAC_BITS
 * of extra fractional precision. Quantising the output back to whole counts on every
 * sample would feed rounding error into a recursive loop, where it accumulates rather
 * than averaging out.
 */
#ifndef VS_NOTCH_H
#define VS_NOTCH_H

#include <stdbool.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Extra fractional bits carried inside the filter state. 8 keeps the recursive path
 * well clear of its own rounding noise; the accumulator is int64 either way. */
#define VS_NOTCH_SAMPLE_FRAC_BITS 8

typedef struct {
    int64_t s1; /* transposed direct-form II state */
    int64_t s2;
    bool primed;
} vs_notch_t;

/* Zero the filter. A filter started from zero rings as it charges through the
 * electrode's DC offset; prefer vs_notch_prime() when the standing level is known. */
void vs_notch_reset(vs_notch_t *f);

/* Set the state to the steady state for a constant input of `counts`, so the first
 * real sample emerges already settled. This is the fixed-point equivalent of scipy's
 * lfilter_zi and of primeWithDC() in the JS port; all three exist for the same reason. */
void vs_notch_prime(vs_notch_t *f, int32_t counts);

/* Filter one sample. Input and output are ADC counts. */
int32_t vs_notch_process(vs_notch_t *f, int32_t counts);

/* Filter a block in place. */
void vs_notch_process_block(vs_notch_t *f, int32_t *counts, uint32_t n);

#ifdef __cplusplus
}
#endif

#endif /* VS_NOTCH_H */
