/**
 * Streaming IIR filtering, in cascaded second-order sections.
 *
 * Coefficients are never designed here - they come from `coefficients.js`, which is
 * generated by the Python design code that was validated against MIT-BIH. This file
 * only *applies* them, so the server cannot filter differently from the pipeline the
 * verification report describes.
 *
 * Sections use the transposed direct form II structure: it needs two state variables
 * per section and is the least noise-sensitive of the direct forms in floating point,
 * which matters when four sections are chained.
 */

/** One second-order section: [b0, b1, b2, a0, a1, a2], with a0 normalised to 1. */
export class Biquad {
  /** @param {number[]} coeffs six coefficients [b0,b1,b2,a0,a1,a2] */
  constructor(coeffs) {
    if (!Array.isArray(coeffs) || coeffs.length !== 6) {
      throw new TypeError(`biquad needs 6 coefficients, got ${coeffs?.length}`);
    }
    const [b0, b1, b2, a0, a1, a2] = coeffs;
    if (!Number.isFinite(a0) || a0 === 0) {
      throw new RangeError(`biquad a0 must be non-zero and finite, got ${a0}`);
    }
    // Normalise by a0 so the difference equation below can assume a0 === 1.
    this.b0 = b0 / a0;
    this.b1 = b1 / a0;
    this.b2 = b2 / a0;
    this.a1 = a1 / a0;
    this.a2 = a2 / a0;
    this.s1 = 0;
    this.s2 = 0;
  }

  /** Zero the filter memory. */
  reset() {
    this.s1 = 0;
    this.s2 = 0;
  }

  /**
   * Load the state this section would settle into for a constant input `x`.
   *
   * Starting from zero state makes the filter "charge up" from the electrode's DC
   * offset, ringing for a second or more and producing beat detections that are
   * artefacts of the filter rather than the patient. Priming removes that
   * transient - it is the streaming equivalent of scipy's `lfilter_zi`.
   *
   * @param {number} x the constant input to settle against
   * @returns {number} the steady-state output for that input (the next section's input)
   */
  primeWithDC(x) {
    // At DC (z = 1) the section's gain is (b0+b1+b2) / (1+a1+a2).
    const denom = 1 + this.a1 + this.a2;
    const gain = Math.abs(denom) < 1e-12 ? 0 : (this.b0 + this.b1 + this.b2) / denom;
    const y = gain * x;
    // Solve the transposed-DF2 state equations for a steady state.
    this.s2 = this.b2 * x - this.a2 * y;
    this.s1 = this.b1 * x - this.a1 * y + this.s2;
    return y;
  }

  /**
   * Filter one sample.
   * @param {number} x
   * @returns {number}
   */
  process(x) {
    const y = this.b0 * x + this.s1;
    this.s1 = this.b1 * x - this.a1 * y + this.s2;
    this.s2 = this.b2 * x - this.a2 * y;
    return y;
  }
}

/** A chain of biquads applied in series. */
export class SosCascade {
  /** @param {number[][]} sos array of [b0,b1,b2,a0,a1,a2] rows */
  constructor(sos) {
    if (!Array.isArray(sos) || sos.length === 0) {
      throw new TypeError('SosCascade needs at least one section');
    }
    this.sections = sos.map((row) => new Biquad(row));
    this.primed = false;
  }

  reset() {
    for (const s of this.sections) s.reset();
    this.primed = false;
  }

  /** Settle every section against a constant input, section by section. */
  primeWithDC(x) {
    let v = x;
    for (const s of this.sections) v = s.primeWithDC(v);
    this.primed = true;
    return v;
  }

  /**
   * Filter one sample through the whole cascade.
   * On the very first sample the cascade primes itself against that sample, so a
   * large DC offset does not ring through the output.
   */
  processSample(x) {
    if (!this.primed) this.primeWithDC(x);
    let v = x;
    for (const s of this.sections) v = s.process(v);
    return v;
  }

  /**
   * Filter a block of samples.
   * @param {ArrayLike<number>} samples
   * @returns {Float64Array}
   */
  process(samples) {
    const out = new Float64Array(samples.length);
    for (let i = 0; i < samples.length; i += 1) out[i] = this.processSample(samples[i]);
    return out;
  }
}

/**
 * A fixed-length circular buffer of numbers, addressed by absolute sample index.
 *
 * The detector needs to look back at samples from a second or two ago (to snap to an
 * R peak, or to compare slopes) while running forever on a live stream. Indexing by
 * absolute sample number keeps that lookback arithmetic readable, and the buffer
 * bounds memory: a monitor that runs for a week must not grow an array for a week.
 */
export class RingBuffer {
  /** @param {number} capacity number of samples to retain */
  constructor(capacity) {
    if (!Number.isInteger(capacity) || capacity <= 0) {
      throw new RangeError(`capacity must be a positive integer, got ${capacity}`);
    }
    this.capacity = capacity;
    this.data = new Float64Array(capacity);
    this.count = 0; // total samples ever pushed = next absolute index
  }

  push(value) {
    this.data[this.count % this.capacity] = value;
    this.count += 1;
  }

  /** Oldest absolute index still retained. */
  get oldestIndex() {
    return Math.max(0, this.count - this.capacity);
  }

  /** True if absolute index `i` is still in the buffer. */
  has(i) {
    return i >= this.oldestIndex && i < this.count;
  }

  /**
   * Read by absolute sample index.
   * @throws {RangeError} if the sample has already been overwritten
   */
  at(i) {
    if (!this.has(i)) {
      throw new RangeError(
        `sample ${i} is outside the retained window [${this.oldestIndex}, ${this.count})`,
      );
    }
    return this.data[i % this.capacity];
  }

  /** Read a slice by absolute index range, clamped to what is retained. */
  slice(from, to) {
    const lo = Math.max(from, this.oldestIndex);
    const hi = Math.min(to, this.count);
    const out = new Float64Array(Math.max(0, hi - lo));
    for (let i = lo; i < hi; i += 1) out[i - lo] = this.data[i % this.capacity];
    return out;
  }
}

/**
 * Trailing moving-window sum, maintained incrementally.
 *
 * Recomputing a 150 ms window sum at every sample would be O(window) per sample;
 * adding the new sample and subtracting the one leaving the window is O(1), which is
 * what makes this affordable on a microcontroller as well as here.
 */
export class MovingAverage {
  constructor(width) {
    if (!Number.isInteger(width) || width <= 0) {
      throw new RangeError(`width must be a positive integer, got ${width}`);
    }
    this.width = width;
    this.buf = new Float64Array(width);
    this.idx = 0;
    this.sum = 0;
    this.filled = 0;
  }

  reset() {
    this.buf.fill(0);
    this.idx = 0;
    this.sum = 0;
    this.filled = 0;
  }

  /** Push a sample and return the current window mean. */
  process(x) {
    this.sum -= this.buf[this.idx];
    this.buf[this.idx] = x;
    this.sum += x;
    this.idx = (this.idx + 1) % this.width;
    if (this.filled < this.width) this.filled += 1;
    // Divide by samples actually seen, so the first window is an average rather
    // than a value diluted by the zeros it was initialised with.
    return this.sum / this.filled;
  }
}
