// Auto-generated by dsp/export_coefficients.py - do not edit by hand.
// Regenerate with:  python dsp/export_coefficients.py
//
// Shared by the Python validation pipeline, the ESP32 firmware and this server.

export const SAMPLE_RATE_HZ = 360;

/** 50 Hz mains-rejection notch, Q = 30. Normalised so a[0] === 1. */
export const NOTCH = {
  b: [0.985663100363, -1.26714405648, 0.985663100363],
  a: [1, -1.26714405648, 0.971326200726],
};

/**
 * Display path: 0.5-40 Hz Butterworth bandpass, order 4.
 * This is the waveform a clinician looks at - undistorted morphology.
 * Rows are [b0, b1, b2, a0, a1, a2].
 */
export const DISPLAY_SOS = [
  [0.00660487567131, 0.0132097513426, 0.00660487567131, 1, -0.97894906924, 0.264010652765],
  [1, 2, 1, 1, -1.23747710352, 0.612478819928],
  [1, -2, 1, 1, -1.98365367346, 0.9837324069],
  [1, -2, 1, 1, -1.9933805831, 0.993457002822],
];

/**
 * Detection path: 5-15 Hz Butterworth bandpass, order 3.
 * Deliberately NOT the display band - it maximises QRS energy for the beat
 * detector at the cost of waveform fidelity (decision D-07).
 */
export const DETECTION_SOS = [
  [0.000562289281379, 0.00112457856276, 0.000562289281379, 1, -1.81807791069, 0.839099631177],
  [1, 0, -1, 1, -1.82315065102, 0.880921959377],
  [1, -2, 1, 1, -1.94554052283, 0.953800959093],
];

/** Pan-Tompkins timing parameters, in milliseconds unless noted. */
export const QRS_PARAMS = {
  integrationMs: 150,
  refractoryMs: 200,
  twaveMs: 360,
  twaveSlopeFrac: 0.5,
  learningS: 2,
  fiducialMs: 100,
  minSignalStd: 0.01,
};

/**
 * Pulse band for photoplethysmography: 0.5-5 Hz, order 2, covering
 * {MIN_PULSE_BPM}-{MAX_PULSE_BPM} bpm and the first harmonic.
 *
 * Keyed by sample rate, because a PPG front end does not run at the ECG rate: the
 * MAX30102 defaults to 100 Hz and the BIDMC recordings used for validation are 125 Hz.
 * Applying one rate's coefficients to another's stream would silently move the band, so
 * the port refuses a rate that is not in this table rather than designing one at run
 * time (the same rule as D-14).
 */
export const PPG_BANDPASS_SOS = {
  100: [
    [0.0165819316693, 0.0331638633386, 0.0165819316693, 1, -1.62885076857, 0.699463477647],
    [1, -2, 1, 1, -1.95738903954, 0.958531685183],
  ],
  125: [
    [0.010993221439, 0.021986442878, 0.010993221439, 1, -1.70463990487, 0.75126731643],
    [1, -2, 1, 1, -1.9659599663, 0.966694616734],
  ],
};

/** Thresholds from dsp/ppg.py - defined once, applied identically in both languages. */
export const PPG_PARAMS = {
  calIntercept: 110,
  calSlope: 25,
  minPerfusionPct: 0.15,
  minPlausibleR: 0.3,
  maxPlausibleR: 3,
  minPulseBpm: 25,
  maxPulseBpm: 240,
  minChannelCorr: 0.97,
  goodChannelCorr: 0.995,
  subharmonicTolerance: 0.5,
  minPeriodicity: 0.5,
};
